### ISSUE TITLE
prompt "what can you do?"

### ISSUE THREAD

**Issue by jsedoc** [JHU-COVID-QA/covid-bot-issues#4]
I asked the chatbot the question "what can you do?"

Bot replied using default: "Information on Covid-19 is constantly changing. You may find responses to questions I currently cannot answer here: https://www.cdc.gov/coronavirus/2019-ncov/index.html . Are there any other questions I can help you with?"

Expected answer should include information about functionality.

![image](https://user-images.githubusercontent.com/5974598/80870050-f9e5c700-8c71-11ea-82ab-544e286c695c.png)

**Comment by edcohen08** [comment]
fixed in [308](https://github.com/jsedoc/Covid-19-infobot/pull/308)

**Comment by jsedoc** [comment]
"tell me what you can do." still fails

**Comment by edcohen08** [comment]
fixed in the most recent push to 308. try on dev. @jsedoc
