### ISSUE TITLE
"Source:" on "Did that answer your question" card

### ISSUE THREAD

**Issue by jsedoc** [JHU-COVID-QA/covid-bot-issues#5]
The "Did that answer your question?" follow up card has **Source:**

I think we don't want this anymore.

![image](https://user-images.githubusercontent.com/5974598/80961374-d5582f00-8dd8-11ea-8632-74f9941c5e70.png)

**Comment by edcohen08** [comment]
That is no longer in https://github.com/jsedoc/Covid-19-infobot/blob/master/src/middleware/app/dialogflow.py so I'm not sure where it's coming from. @jsedoc @arpansahoo

**Comment by edcohen08** [comment]
Nevermind that came from a built in one.
